MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MB.AgilePortfolio.BL;

namespace MB.AgilePortfolio.MVCUI.Controllers
{
    public class PrivacyController : Controller
    {
        Privacy privacy;
        PrivacyList privacies;
        
        // GET: Privacy
        public ActionResult Index()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            privacies = new PrivacyList();
            privacies.Load();
            return View(privacies);
        }

        // GET: Privacy/Details/5
        public ActionResult Details(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            privacy = new Privacy();
            privacy.LoadById(id);
            return View(privacy);
        }

        // GET: Privacy/Create
        public ActionResult Create()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            privacy = new Privacy();
            return View(privacy);
        }

        // POST: Privacy/Create
        [HttpPost]
        public ActionResult Create(Privacy p)
        {
            try
            {
                // TODO: Add insert logic here
                p.Insert();
                return RedirectToAction("Index");
            }
            catch { return View(p); }
        }

        // GET: Privacy/Edit/5
        public ActionResult Edit(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            privacy = new Privacy();
            privacy.LoadById(id);
            return View(privacy);
        }

        // POST: Privacy/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, Privacy p)
        {
            try
            {
                // TODO: Add update logic here
                p.Update();
                return RedirectToAction("Index");
            }
            catch { return View(p); }
        }

        // GET: Privacy/Delete/5
        public ActionResult Delete(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            privacy = new Privacy();
            privacy.LoadById(id);
            return View(privacy);
        }

        // POST: Privacy/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, Privacy p)
        {
            try
            {
                // TODO: Add delete logic here
                p.Delete();
                return RedirectToAction("Index");
            }
            catch { return View(p); }
        }
    }
}

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MB.AgilePortfolio.BL;
using MB.AgilePortfolio.MVCUI.ViewModels;

namespace MB.AgilePortfolio.MVCUI.Controllers
{
    public class ProjectController : Controller
    {
        Project project;
        ProjectList projects;

        // GET: Project
        public ActionResult Index()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            projects = new ProjectList();
            projects.Load();
            return View(projects);
        }

        // GET: Project/Details/5
        public ActionResult Details(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            project = new Project();
            project.LoadById(id);


            return View(project);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            ProjectPrivaciesUsersStatuses ppus = new ProjectPrivaciesUsersStatuses()
            {
                Project = new Project(),
                Privacies = new PrivacyList(),
                Users = new UserList(),
                Statuses = new StatusList()
            };
            ppus.Privacies.Load();
            ppus.Users.Load();
            ppus.Statuses.Load();
            return View(ppus);
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(ProjectPrivaciesUsersStatuses ppus)
        {

            try
            {
                // TODO: Add insert logic here
                ppus.Project.Insert();
                return RedirectToAction("Index");
            }
            catch { return View(ppus); }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            ProjectPrivaciesUsersStatuses ppus = new ProjectPrivaciesUsersStatuses()
            {
                Project = new Project(),
                Privacies = new PrivacyList(),
                Users = new UserList(),
                Statuses = new StatusList()
            };
            ppus.Project.LoadById(id);
            ppus.Privacies.Load();
            ppus.Users.Load();
            ppus.Statuses.Load();
            return View(ppus);
        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, ProjectPrivaciesUsersStatuses ppus)
        {
            try
            {
                // TODO: Add update logic here
                ppus.Project.Update();
                return RedirectToAction("Index");
            }
            catch { return View(ppus); }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            project = new Project();
            project.LoadById(id);
           
            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, Project p)
        {
            try
            {
                // TODO: Add delete logic here
                p.Delete();
                return RedirectToAction("Index");
            }
            catch { return View(p); }
        }
    }
}

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MB.AgilePortfolio.BL;

namespace MB.AgilePortfolio.MVCUI.Controllers
{
    public class StatusController : Controller
    {
        Status status;
        StatusList statuses;
        
        // GET: Status
        public ActionResult Index()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            statuses = new StatusList();
            statuses.Load();
            return View(statuses);
        }

        // GET: Status/Details/5
        public ActionResult Details(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            status = new Status();
            status.LoadById(id);
            return View(status);
        }

        // GET: Status/Create
        public ActionResult Create()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            status = new Status();
            return View(status);
        }

        // POST: Status/Create
        [HttpPost]
        public ActionResult Create(Status s)
        {
            try
            {
                // TODO: Add insert logic here
                s.Insert();
                return RedirectToAction("Index");
            }
            catch { return View(s); }
        }

        // GET: Status/Edit/5
        public ActionResult Edit(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            status = new Status();
            status.LoadById(id);
            return View(status);
        }

        // POST: Status/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, Status s)
        {
            try
            {
                // TODO: Add update logic here
                s.Update();
                return RedirectToAction("Index");
            }
            catch { return View(s); }
        }

        // GET: Status/Delete/5
        public ActionResult Delete(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            status = new Status();
            status.LoadById(id);
            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, Status s)
        {
            try
            {
                // TODO: Add delete logic here
                s.Delete();
                return RedirectToAction("Index");
            }
            catch { return View(s); }
        }
    }
}

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MB.AgilePortfolio.BL;
using MB.AgilePortfolio.MVCUI.ViewModels;

namespace MB.AgilePortfolio.MVCUI.Controllers
{
    public class UserController : Controller
    {
        User user;
        UserList users;
        
        // GET: User
        public ActionResult Index()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            users = new UserList();
            users.Load();
            return View(users);
        }

        // GET: User/Details/5
        public ActionResult Details(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");

            }
            user = new User();
            user.LoadById(id);
            return View(user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            UserUserTypes uut = new UserUserTypes()
            {
                User = new User(),
                UserTypes = new UserTypeList()
            };
            uut.UserTypes.Load();
            return View(uut);
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(UserUserTypes uut)
        {
            try
            {
                // TODO: Add insert logic here
                uut.User.Insert();
                return RedirectToAction("Index");
            }
            catch { return View(uut); }
        }

        // GET: User/Edit/5
        public ActionResult Edit(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            UserUserTypes uut = new UserUserTypes()
            {
                User = new User(),
                UserTypes = new UserTypeList()
            };
            uut.User.LoadById(id);
            uut.UserTypes.Load();
            return View(uut);
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, UserUserTypes uut)
        {
            try
            {
                // TODO: Add update logic here
                uut.User.Update();
                return RedirectToAction("Index");
            }
            catch { return View(uut); }
        }

        // GET: User/Delete/5
        public ActionResult Delete(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            user = new User();
            user.LoadById(id);
            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, User u)
        {
            try
            {
                // TODO: Add delete logic here
                u.Delete();
                return RedirectToAction("Index");
            }
            catch { return View(u); }
        }
    }
}

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Views/Admin/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin</h2>

<div class="row">
    <table class="table col-md-12 text-center">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Object</th>
                <th scope="col">View All</th>
                <th scope="col">Add New</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Languages</td>
                <td>
                    <a href="@Url.Action("Index", "Language")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Language")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Portfolios</td>
                <td>
                    <a href="@Url.Action("Index", "Portfolio")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Portfolio")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Projects</td>
                <td>
                    <a href="@Url.Action("Index", "Project")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Project")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">4</th>
                <td>Privacies</td>
                <td>
                    <a href="@Url.Action("Index", "Privacy")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Privacy")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">5</th>
                <td>Screenshots</td>
                <td>
                    <a href="@Url.Action("Index", "Screenshot")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Screenshot")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">6</th>
                <td>Statuses</td>
                <td>
                    <a href="@Url.Action("Index", "Status")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Status")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">7</th>
                <td>Users</td>
                <td>
                    <a href="@Url.Action("Index", "User")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "User")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">8</th>
                <td>UserTypes</td>
                <td>
                    <a href="@Url.Action("Index", "UserType")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "UserType")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin</h2>

<div class="row">
    <table class="table col-md-12 text-center">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Object</th>
                <th scope="col">View All</th>
                <th scope="col">Add New</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Languages</td>
                <td>
                    <a href="@Url.Action("Index", "Language")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Language")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Portfolios</td>
                <td>
                    <a href="@Url.Action("Index", "Portfolio")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Portfolio")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Projects</td>
                <td>
                    <a href="@Url.Action("Index", "Project")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Project")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">4</th>
                <td>Privacies</td>
                <td>
                    <a href="@Url.Action("Index", "Privacy")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Privacy")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">5</th>
                <td>Screenshots</td>
                <td>
                    <a href="@Url.Action("Index", "Screenshot")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Screenshot")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">6</th>
                <td>Statuses</td>
                <td>
                    <a href="@Url.Action("Index", "Status")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "Status")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">7</th>
                <td>Users</td>
                <td>
                    <a href="@Url.Action("Index", "User")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "User")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">8</th>
                <td>UserTypes</td>
                <td>
                    <a href="@Url.Action("Index", "UserType")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "UserType")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="row">9</th>
                <td>PortfolioProjects</td>
                <td>
                    <a href="@Url.Action("Index", "PortfolioProject")">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Create", "PortfolioProject")">
                        <i class="fa fa-plus-square"></i>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>