MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/ViewModels/UploadedImages.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MB.AgilePortfolio.BL;

namespace MB.AgilePortfolio.MVCUI.ViewModels
{
    public class UploadedImages
    {
        public string FilePath { get; set; }
        public HttpPostedFileBase Fileupload { get; set; }
        public string ObjectType { get; set; }
        public string ObjectName { get; set; }
        public string UserName { get; set; }
        public UploadedImage UploadedImage { get; set; }
    }
}

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Controllers/ScreenshotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MB.AgilePortfolio.BL;
using MB.AgilePortfolio.MVCUI.ViewModels;
using MB.AgilePortfolio.MVCUI.Models;
using System.IO;
using System.Text;

namespace MB.AgilePortfolio.MVCUI.Controllers
{
    public class ScreenshotController : Controller
    {
        ScreenshotList screenshots;

        // GET: Screenshot
        public ActionResult Index()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            screenshots = new ScreenshotList();
            screenshots.Load();
            return View(screenshots);
        }

        // GET: Screenshot/Details/5
        public ActionResult Details(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            ScreenshotProjects sp = new ScreenshotProjects()
            {
                Screenshot = new Screenshot(),
                Projects = new ProjectList()
            };
            sp.Projects.Load();
            sp.Screenshot.LoadById(id);

            return View(sp);
        }

        // GET: Screenshot/Create
        public ActionResult Create()
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            ScreenshotProjects sp = new ScreenshotProjects()
            {
                Screenshot = new Screenshot(),
                Projects = new ProjectList()
            };
            sp.Projects.Load();
            return View(sp);
        }

        // POST: Screenshot/Create
        [HttpPost]
        public ActionResult Create(ScreenshotProjects sp)
        {
            try
            {
                // TODO: Add insert logic here
                sp.Screenshot.Insert();
                return RedirectToAction("Index");
            }
            catch { return View(sp); }
        }

        // GET: Screenshot/Edit/5
        public ActionResult Edit(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null || userin.UserTypeDescription != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            ScreenshotProjects sp = new ScreenshotProjects()
            {
                Screenshot = new Screenshot(),
                Projects = new ProjectList()
            };
            sp.Projects.Load();
            sp.Screenshot.LoadById(id);
            return View(sp);
        }

        // POST: Screenshot/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, ScreenshotProjects sp)
        {
            try
            {
                // TODO: Add update logic here
                sp.Screenshot.Update();
                return RedirectToAction("Index");
            }
            catch { return View(sp); }
        }


        // GET: Screenshot/Delete/5
        public ActionResult Delete(Guid id)
        {
            User userin = System.Web.HttpContext.Current.Session["user"] as User;
            if (userin == null)
            {
                return RedirectToAction("Index", "Home");
            }

            ScreenshotProjects sp = new ScreenshotProjects()
            {
                Projects = new ProjectList(),
                Screenshot = new Screenshot()
            };
            ProjectList pl = new ProjectList();
            pl.Load();

            sp.Projects = pl;
            Screenshot ss = new Screenshot();
            ss.LoadById(id);
            sp.Screenshot = ss;

            return View(sp);
        }

        // POST: Screenshot/Delete/5
        [HttpPost]
        //public ActionResult Delete(Guid screenShotId, ScreenshotProjects sp)
        public ActionResult Delete(Guid screenShotId, Guid projectId)
        {
            try
            {

                var screenShot = Screenshot.StaticLoadById(screenShotId);
                var fullPath = Server.MapPath("~/" + screenShot.FilePath);

                Screenshot.Delete(screenShotId);

                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                    ViewBag.deleteSuccess = "true";
                }
            }
            catch (Exception e)
            {

            }
            return RedirectToAction("UploadProjectSliderImage", new { id = projectId });
        }

        // GET: Admin
        public ActionResult UploadProjectSliderImage(Guid? id)
        {
            if (Authenticate.IsAuthenticated())
            {
                Guid ID = id.GetValueOrDefault();
                if (ID == Guid.Empty)
                {
                    if (Authenticate.IsAuthenticated())
                    {
                        return RedirectToAction("EditProjects", "UserProfile", new { returnurl = HttpContext.Request.Url });
                    }
                    else
                    {
                        return RedirectToAction("Index", "Login", new { returnurl = HttpContext.Request.Url });
                    }
                }
                ScreenshotProjects sp = new ScreenshotProjects()
                {
                    Screenshot = new Screenshot(),
                    ScreenshotList = new ScreenshotList()
                };
                sp.ProjectId = ID;
                sp.ScreenshotList.LoadbyProjectID(ID);
                return View(sp);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }


        [HttpPost]
        public ActionResult UploadProjectSliderImage(Guid id, ScreenshotProjects sp)
        {
            
            HttpPostedFileBase fileupload = sp.Fileupload;
            if (fileupload != null)
            {
                User userin = System.Web.HttpContext.Current.Session["user"] as User;
                string username = userin.Username;
                string strUserID = userin.Id.ToString();
                string fileName = Path.GetFileName(fileupload.FileName);
                string savepath = "";
                if (Directory.Exists("~/Assets/Images/ScreenShots"))
                {
                    savepath = "Assets/Images/ScreenShots/" + username;
                }
                else
                {
                    Directory.CreateDirectory(Server.MapPath("~/Assets/Images/ScreenShots/" + username));
                    savepath = "Assets/Images/ScreenShots/" + username;
                }
                Project p = new Project();
                p.LoadById(id);
                sp.Project = p;
                if (Directory.Exists("~/Assets/Images/ScreenShots/{username}/{sp.Project.Name}"))
                {
                    savepath = $"Assets/Images/ScreenShots/{username}/{sp.Project.Name}";
                }
                else
                {
                    Directory.CreateDirectory(Server.MapPath($"~/Assets/Images/ScreenShots/{username}/{sp.Project.Name}"));
                    savepath = $"Assets/Images/ScreenShots/{username}/{sp.Project.Name}";
                }


                Screenshot ss = new Screenshot();

                ss.ProjectId = id;


                // ss.FilePath = Server.MapPath(~Assets/Images/ScreenShots/" + username + "/" + fileName);


                fileupload.SaveAs(Server.MapPath("~/" + savepath + "/" + fileName));
                ss.FilePath = savepath + "/" + fileName;
                ss.Insert();
            }
            return RedirectToAction("UploadProjectSliderImage");
        }

        // GET: UserProfile/EditProject
        public ActionResult EditProject(Guid? id)
        {
            Guid ID = id.GetValueOrDefault();
            if (ID == Guid.Empty)
            {
                if (Authenticate.IsAuthenticated())
                {

                    return RedirectToAction("EditProjects", "UserProfile", new { returnurl = HttpContext.Request.Url });
                }
                else
                {
                    return RedirectToAction("Index", "Login", new { returnurl = HttpContext.Request.Url });
                }
            }
            else
            {
                ScreenshotProjects up = new ScreenshotProjects()
                {
                    SelectedLanguages = new List<string>(),
                    AvailableLanguages = new List<SelectListItem>(),
                    Project = new Project(),
                    Privacies = new PrivacyList(),
                    User = new User(),
                    Statuses = new StatusList(),
                    ScreenshotList = new ScreenshotList(),
                    Languages = new LanguageList(),
                    ProjectLanguage = new ProjectLanguage(),
                    ProjectLanguages = new ProjectLanguageList()
                };

                if (Authenticate.IsAuthenticated())
                {
                    up.Project.LoadById(ID);
                    Project project = new Project();
                    project.LoadById(up.Project.Id);
                    up.DateCreated = project.DateCreated;
                    up.LastUpdated = project.LastUpdated;
                    up.Languages.Load();
                    up.AvailableLanguages = GetLanguages(up.Languages);
                    up.Privacies.Load();
                    User userin = System.Web.HttpContext.Current.Session["user"] as User;
                    up.User.LoadById(userin.Id);

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Views/UploadedImage/Index.cshtml
@model IEnumerable<MB.AgilePortfolio.BL.Screenshot>

@{
    ViewBag.Title = "Screenshots";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Screenshots</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FilePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FilePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MB.AgilePortfolio/MB.AgilePortfolio.MVCUI/Views/UploadedImage/UploadProjectSliderImage.cshtml
@model MB.AgilePortfolio.MVCUI.ViewModels.ScreenshotProjects
@{
    ViewBag.Title = "Upload Project Images";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload Project Images</title>
    <script src="~/scripts/jquery-3.3.1.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="~/scripts/jquery.dataTables.min.js"></script>
    <script src="~/scripts/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#dataTable").dataTable();
        });
    </script>
    <style>
        .carousel-inner img {
            width: 100%;
            height: 350px;
        }
    </style>
</head>
<body>


    <div class="container py-4">
        @{ string title = "";}
        @foreach (var item in Model.ScreenshotList)
        {
            title = item.ProjectName;
        }

        <div id="demo" class="carousel slide" data-ride="carousel">
            <ul class="carousel-indicators">

                @foreach (var item in Model.ScreenshotList.Select((value, a) => new { a, value }))
                {
                    if (item.a == 0)
                    {
                        <li data-target="#demo" data-slide-to="@item.a" class="active"></li>
                    }
                    else
                    {
                        <li data-target="#demo" data-slide-to="@item.a"></li>
                    }

                }
            </ul>
            <div class="carousel-inner" role="listbox">
                @{int i = 0; }
                @foreach (var item in Model.ScreenshotList)
                {
                    i++;
                    var active = i == 1 ? "active" : "";
                    <div class="carousel-item @active">
                        @* <img src="@Url.Content(@item.FilePath)" alt="">*@
                        <img src="~/@item.FilePath" alt="">
                    </div>
                }
            </div>
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h6 class="text-uppercase">@title Images</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    <button style="margin-left: 27px;margin-bottom:10px;" type="button" class="btn btn-primary rounded-0" data-toggle="modal" data-target="#myModal">
                        <i class="fa fa-plus-circle"></i> Add New
                    </button>
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Upload New Image</h4>
                                    <button type="button" class="close" data-dismiss="modal">×</button>
                                </div>
                                <div class="modal-body">
                                    @using (Html.BeginForm("UploadProjectSliderImage", "Screenshot", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        <div class="form-group">
                                            <label>Choose File:</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    @Html.TextBoxFor(model => model.Fileupload, new { type = "file", id = "fileupload", name = "fileupload", accept = ".jpg, .jpeg, .gif, .png" })
                                                </div>
                                                <div class="input-group-append">
                                                    <input type="submit" id="btnUpload" class="btn btn-secondary" value="Upload" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <table id="dataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Image Path</th>
                            <th>Thumbnail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ScreenshotList)
                        {
                            string[] pathArr = item.FilePath.Split('/');
                            string Fp = pathArr.Last().ToString();
                            <tr>
                                <td>@Fp</td>
                                <td>
                                    <img src="@Url.Content("~/" + @item.FilePath)" alt="" width="80" height="60" class="img-thumbnail" />
                                </td>
                                <td>
                                    @Html.ActionLink(
                                       "Delete",
                                       "Delete",
                                       "Screenshot",

                                       new { id = item.Id },
                                       new { @class = "btn btn-primary"}
                                       )
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>  